"""
main.py
-------
FastAPI service that loads the trained breast-cancer classifier and
exposes a validated /predict endpoint.

Run locally:
    uvicorn main:app --reload --port 8000

Interactive docs (auto-generated by FastAPI):
    http://127.0.0.1:8000/docs
"""

import json
import logging
from pathlib import Path
from typing import List

import joblib
import numpy as np
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field, field_validator

# ---------------------------------------------------------------------------
# Config / constants
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent
MODEL_PATH = PROJECT_ROOT / "model.joblib"
METADATA_PATH = PROJECT_ROOT / "model_metadata.json"

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("model-api")

app = FastAPI(
    title="Breast Cancer Classifier API",
    description="Serves predictions from a Random Forest model trained on "
    "the sklearn Breast Cancer Wisconsin dataset.",
    version="1.0.0",
)


# ---------------------------------------------------------------------------
# Load model + metadata once at startup (reusable, not per-request)
# ---------------------------------------------------------------------------
def load_model_artifacts():
    """Load the trained pipeline and its metadata from disk."""
    if not MODEL_PATH.exists() or not METADATA_PATH.exists():
        raise FileNotFoundError(
            "Model artifacts not found. Run `python train_model.py` first."
        )

    model = joblib.load(MODEL_PATH)
    with open(METADATA_PATH) as f:
        metadata = json.load(f)

    # Validation check: model's expected feature count must match metadata
    n_expected = metadata["n_features"]
    assert model.named_steps["classifier"].n_features_in_ == n_expected, (
        "Loaded model feature count does not match metadata."
    )
    logger.info(f"Loaded model expecting {n_expected} features.")
    return model, metadata


model, metadata = load_model_artifacts()
FEATURE_NAMES: List[str] = metadata["feature_names"]
TARGET_NAMES: List[str] = metadata["target_names"]
N_FEATURES: int = metadata["n_features"]


# ---------------------------------------------------------------------------
# Request / response schemas (validation happens here via Pydantic)
# ---------------------------------------------------------------------------
class PredictionRequest(BaseModel):
    """
    Input schema for a single prediction.

    `features` must contain exactly N_FEATURES numeric values, in the
    same order as FEATURE_NAMES (see GET /features for the exact order).
    """

    features: List[float] = Field(
        ...,
        description=f"Exactly {N_FEATURES} numeric feature values, "
        f"ordered per GET /features.",
        min_length=N_FEATURES,
        max_length=N_FEATURES,
    )

    @field_validator("features")
    @classmethod
    def check_finite(cls, values: List[float]) -> List[float]:
        if any(v is None for v in values):
            raise ValueError("features cannot contain null values.")
        arr = np.array(values, dtype=float)
        if not np.all(np.isfinite(arr)):
            raise ValueError("features must all be finite numbers (no NaN/inf).")
        return values


class PredictionResponse(BaseModel):
    predicted_class: str
    predicted_class_index: int
    confidence: float
    class_probabilities: dict


class HealthResponse(BaseModel):
    status: str
    model_type: str
    n_features_expected: int
    test_accuracy: float


# ---------------------------------------------------------------------------
# Reusable prediction function (kept separate from the route for testability)
# ---------------------------------------------------------------------------
def predict(features: List[float]) -> PredictionResponse:
    X = np.array(features, dtype=float).reshape(1, -1)
    pred_index = int(model.predict(X)[0])
    probabilities = model.predict_proba(X)[0]

    class_probabilities = {
        TARGET_NAMES[i]: round(float(p), 6) for i, p in enumerate(probabilities)
    }

    return PredictionResponse(
        predicted_class=TARGET_NAMES[pred_index],
        predicted_class_index=pred_index,
        confidence=round(float(probabilities[pred_index]), 6),
        class_probabilities=class_probabilities,
    )


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------
@app.get("/", tags=["Info"])
def root():
    return {
        "message": "Breast Cancer Classifier API is running.",
        "docs": "/docs",
        "health": "/health",
        "features": "/features",
        "predict": "POST /predict",
    }


@app.get("/health", response_model=HealthResponse, tags=["Info"])
def health():
    """Reports service and model status."""
    return HealthResponse(
        status="ok",
        model_type=metadata["model_type"],
        n_features_expected=N_FEATURES,
        test_accuracy=metadata["test_accuracy"],
    )


@app.get("/features", tags=["Info"])
def get_feature_order():
    """Returns the exact ordered list of feature names the model expects."""
    return {"n_features": N_FEATURES, "feature_names": FEATURE_NAMES}


@app.post("/predict", response_model=PredictionResponse, tags=["Prediction"])
def predict_endpoint(request: PredictionRequest):
    """
    Predict the class (malignant / benign) for one sample.

    Pydantic validates that `features` is present, is a list of floats,
    contains exactly N_FEATURES values, and has no null/NaN/inf entries
    before this function body ever runs. Any violation returns HTTP 422
    automatically with a description of what failed.
    """
    try:
        return predict(request.features)
    except Exception as exc:  # defensive: surfaces unexpected model errors as 500
        logger.exception("Prediction failed")
        raise HTTPException(status_code=500, detail=f"Prediction failed: {exc}")
